sonar.projectKey=Java-Idl_dfms
sonar.organization=java-idl
sonar.sources=app,fuzz,scripts
sonar.tests=tests
sonar.exclusions=app/command_service_v0.py,**/__pycache__/**,**/.venv/**
sonar.python.version=3.12
